# Security baseline generated by repo-harden codify {{.Version}}
# https://github.com/26zl/repo-harden
#
# Works with Terraform >= 1.5 and OpenTofu >= 1.6 (config-driven import).
# These resources describe the four hardening controls supported directly by
# the GitHub provider. Safe narrower Actions settings are preserved. Codify
# refuses same-name rulesets whose extra policy would be lost. Always review
# `plan`: imports can still update resources to reach the desired state.
# CodeQL, secret scanning, default token permissions, and private vulnerability
# reporting remain managed by `repo-harden harden` because provider v6 has no
# dedicated resources for those settings.

terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}
{{- range .Owners}}

provider "github" {
  alias = "{{.TFName}}"
  owner = "{{hcl .Login}}"
}
{{- range .Repos}}

# --- {{.Name}} ---

{{if .ActionsEnabled}}resource "github_actions_repository_permissions" "{{.TFName}}" {
  provider             = github.{{.OwnerTFName}}
  repository           = "{{hcl .Name}}"
  enabled              = {{.ActionsEnabled}}
  allowed_actions      = "{{.ActionsPolicy}}"
  sha_pinning_required = {{.ActionsSHAPinning}}

{{if .ActionsSelected}}
  allowed_actions_config {
    github_owned_allowed = {{.ActionsGithubOwned}}
    verified_allowed     = {{.ActionsVerified}}
    patterns_allowed     = {{hclStrings .ActionsPatterns}}
  }
{{end}}
}{{else}}resource "github_actions_repository_permissions" "{{.TFName}}" {
  provider   = github.{{.OwnerTFName}}
  repository = "{{hcl .Name}}"
  enabled    = false
}{{end}}

import {
  provider = github.{{.OwnerTFName}}
  to       = github_actions_repository_permissions.{{.TFName}}
  id       = "{{hcl .Name}}"
}

resource "github_repository_dependabot_security_updates" "{{.TFName}}" {
  provider   = github.{{.OwnerTFName}}
  repository = "{{hcl .Name}}"
  enabled    = true
}

resource "github_repository_vulnerability_alerts" "{{.TFName}}" {
  provider   = github.{{.OwnerTFName}}
  repository = "{{hcl .Name}}"
  enabled    = true
}

import {
  provider = github.{{.OwnerTFName}}
  to       = github_repository_vulnerability_alerts.{{.TFName}}
  id       = "{{hcl .Name}}"
}

import {
  provider = github.{{.OwnerTFName}}
  to       = github_repository_dependabot_security_updates.{{.TFName}}
  id       = "{{hcl .Name}}"
}

resource "github_repository_ruleset" "{{.TFName}}" {
  provider    = github.{{.OwnerTFName}}
  name        = "{{$.RulesetName}}"
  repository  = "{{hcl .Name}}"
  target      = "branch"
  enforcement = "active"

  conditions {
    ref_name {
      include = ["~DEFAULT_BRANCH"]
      exclude = []
    }
  }

  rules {
    deletion                = true
    non_fast_forward        = true
    required_linear_history = true

    pull_request {
      required_approving_review_count   = 0
      required_review_thread_resolution = true
    }
  }
}
{{- if .RulesetID}}

import {
  provider = github.{{.OwnerTFName}}
  to       = github_repository_ruleset.{{.TFName}}
  id       = "{{hcl .Name}}:{{.RulesetID}}"
}
{{- end}}
{{- end}}
{{- end}}
